---
abstract: "PYX class for line oriented output for 'Tags'."
author:
  - 'Michal Spacek <skim@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  File::Object: 0.05
  Test::More: 0
  Test::NoWarnings: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.14'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tags-Output-PYX
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  Error::Pure: 0
  Readonly: 0
  Tags::Output: 0
  Tags::Utils: 0
  perl: 5.6.2
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Tags-Output-PYX
  homepage: https://github.com/tupinek/Tags-Output-PYX
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/tupinek/Tags-Output-PYX
version: '0.01'
